const carDetailModels = [
  {
    carName: '아반떼',
    detailModels: [
      {
        carName: '아반떼',
        modelName: 'Smart',
        price: 19940000,
        imageSrc: 'https://www.hyundai.com//contents/vr360/CN17/trim/RB.png',
        interiorSrc: 'https://www.hyundai.com/contents/vr360/NE04/interior/I58/img-interior.png',
        catalogSrc: 'https://www.hyundai.com/kr/ko/e/vehicles/avante/catalog',
      },
      {
        carName: '아반떼',
        modelName: 'Modern',
        price: 23260000,
        imageSrc: 'https://www.hyundai.com//contents/vr360/CN17/trim/RD.png',
        interiorSrc: 'https://www.hyundai.com/contents/vr360/NE04/interior/I58/img-interior.png',
        catalogSrc: 'https://www.hyundai.com/kr/ko/e/vehicles/avante/catalog',
      },
      {
        carName: '아반떼',
        modelName: 'N Line Modern',
        price: 24460000,
        imageSrc: 'https://www.hyundai.com//contents/vr360/CN17/trim/RF.png',
        interiorSrc: 'https://www.hyundai.com/contents/vr360/NE04/interior/I58/img-interior.png',
        catalogSrc: 'https://www.hyundai.com/kr/ko/e/vehicles/avante/catalog',
      },
      {
        carName: '아반떼',
        modelName: 'Inspiration',
        price: 26990000,
        imageSrc: 'https://www.hyundai.com//contents/vr360/CN17/trim/RG.png',
        interiorSrc: 'https://www.hyundai.com/contents/vr360/NE04/interior/I58/img-interior.png',
        catalogSrc: 'https://www.hyundai.com/kr/ko/e/vehicles/avante/catalog',
      },
      {
        carName: '아반떼',
        modelName: 'N Line Inspiration',
        price: 27880000,
        imageSrc: 'https://www.hyundai.com//contents/vr360/CN17/trim/RK.png',
        interiorSrc: 'https://www.hyundai.com/contents/vr360/NE04/interior/I58/img-interior.png',
        catalogSrc: 'https://www.hyundai.com/kr/ko/e/vehicles/avante/catalog',
      },
    ],
  },
  {
    carName: '쏘나타 디 엣지',
    detailModels: [
      {
        carName: '쏘나타 디 엣지',
        modelName: 'Premium',
        price: 27180000,
        imageSrc: 'https://www.hyundai.com/contents/vr360/DN20/trim/RB.png',
        interiorSrc: 'https://www.hyundai.com/contents/vr360/NE04/interior/I58/img-interior.png',
        catalogSrc: 'https://www.hyundai.com/kr/ko/e/vehicles/sonata/catalog',
      },
      {
        carName: '쏘나타 디 엣지',
        modelName: 'Exclusive',
        price: 29210000,
        imageSrc: 'https://www.hyundai.com/contents/vr360/DN20/trim/RC.png',
        interiorSrc: 'https://www.hyundai.com/contents/vr360/NE04/interior/I58/img-interior.png',
        catalogSrc: 'https://www.hyundai.com/kr/ko/e/vehicles/sonata/catalog',
      },
      {
        carName: '쏘나타 디 엣지',
        modelName: 'Inspiration',
        price: 34210000,
        imageSrc: 'https://www.hyundai.com/contents/vr360/DN20/trim/RE.png',
        interiorSrc: 'https://www.hyundai.com/contents/vr360/NE04/interior/I58/img-interior.png',
        catalogSrc: 'https://www.hyundai.com/kr/ko/e/vehicles/sonata/catalog',
      },
    ],
  },
  {
    carName: '그랜저',
    detailModels: [
      {
        carName: '그랜저',
        modelName: 'Premium',
        price: 37890000,
        imageSrc: 'https://www.hyundai.com/contents/vr360/GN05/trim/RA.png',
        interiorSrc: 'https://www.hyundai.com/contents/vr360/NE04/interior/I58/img-interior.png',
        catalogSrc: 'https://www.hyundai.com/kr/ko/e/vehicles/grandeur/catalog',
      },
      {
        carName: '그랜저',
        modelName: 'Exclusive',
        price: 41320000,
        imageSrc: 'https://www.hyundai.com/contents/vr360/GN05/trim/RB.png',
        interiorSrc: 'https://www.hyundai.com/contents/vr360/NE04/interior/I58/img-interior.png',
        catalogSrc: 'https://www.hyundai.com/kr/ko/e/vehicles/grandeur/catalog',
      },
      {
        carName: '그랜저',
        modelName: 'Calligraphy',
        price: 45370000,
        imageSrc: 'https://www.hyundai.com/contents/vr360/GN05/trim/RC.png',
        interiorSrc: 'https://www.hyundai.com/contents/vr360/NE04/interior/I58/img-interior.png',
        catalogSrc: 'https://www.hyundai.com/kr/ko/e/vehicles/grandeur/catalog',
      },
    ],
  },
  {
    carName: '투싼',
    detailModels: [
      {
        carName: '투싼',
        modelName: 'Modern',
        price: 30130000,
        imageSrc: 'https://www.hyundai.com/contents/vr360/NX13/trim/DD.png',
        interiorSrc: 'https://www.hyundai.com/contents/vr360/NE04/interior/I58/img-interior.png',
        catalogSrc: 'https://www.hyundai.com/kr/ko/e/vehicles/tucson/catalog',
      },
      {
        carName: '투싼',
        modelName: 'Premium',
        price: 33100000,
        imageSrc: 'https://www.hyundai.com/contents/vr360/NX13/trim/DC.png',
        interiorSrc: 'https://www.hyundai.com/contents/vr360/NE04/interior/I58/img-interior.png',
        catalogSrc: 'https://www.hyundai.com/kr/ko/e/vehicles/tucson/catalog',
      },
      {
        carName: '투싼',
        modelName: '프리미엄 N line',
        price: 34850000,
        imageSrc: 'https://www.hyundai.com/contents/vr360/NX13/trim/DN.png',
        interiorSrc: 'https://www.hyundai.com/contents/vr360/NE04/interior/I58/img-interior.png',
        catalogSrc: 'https://www.hyundai.com/kr/ko/e/vehicles/tucson/catalog',
      },
      {
        carName: '투싼',
        modelName: 'Inspiration',
        price: 36810000,
        imageSrc: 'https://www.hyundai.com/contents/vr360/NX13/trim/DP.png',
        interiorSrc: 'https://www.hyundai.com/contents/vr360/NE04/interior/I58/img-interior.png',
        catalogSrc: 'https://www.hyundai.com/kr/ko/e/vehicles/tucson/catalog',
      },
      {
        carName: '투싼',
        modelName: '인스퍼레이션 N line',
        price: 37810000,
        imageSrc: 'https://www.hyundai.com/contents/vr360/NX13/trim/DM.png',
        interiorSrc: 'https://www.hyundai.com/contents/vr360/NE04/interior/I58/img-interior.png',
        catalogSrc: 'https://www.hyundai.com/kr/ko/e/vehicles/tucson/catalog',
      },
    ],
  },
  {
    carName: '팰리세이드',
    detailModels: [
      {
        carName: '팰리세이드',
        modelName: 'Le Blanc(르블랑)',
        price: 43460000,
        imageSrc: 'https://www.hyundai.com/contents/vr360/LX06/trim/DS.png',
        interiorSrc: 'https://www.hyundai.com/contents/vr360/NE04/interior/I58/img-interior.png',
        catalogSrc: 'https://www.hyundai.com/kr/ko/e/vehicles/the-all-new-palisade/catalog',
      },
      {
        carName: '팰리세이드',
        modelName: 'Exclusive',
        price: 40440000,
        imageSrc: 'https://www.hyundai.com/contents/vr360/LX06/trim/DA.png',
        interiorSrc: 'https://www.hyundai.com/contents/vr360/NE04/interior/I58/img-interior.png',
        catalogSrc: 'https://www.hyundai.com/kr/ko/e/vehicles/the-all-new-palisade/catalog',
      },
      {
        carName: '팰리세이드',
        modelName: 'Prestige',
        price: 47720000,
        imageSrc: 'https://www.hyundai.com/contents/vr360/LX06/trim/DB.png',
        interiorSrc: 'https://www.hyundai.com/contents/vr360/NE04/interior/I58/img-interior.png',
        catalogSrc: 'https://www.hyundai.com/kr/ko/e/vehicles/the-all-new-palisade/catalog',
      },
      {
        carName: '팰리세이드',
        modelName: 'Calligraphy',
        price: 52540000,
        imageSrc: 'https://www.hyundai.com/contents/vr360/LX06/trim/DC.png',
        interiorSrc: 'https://www.hyundai.com/contents/vr360/NE04/interior/I58/img-interior.png',
        catalogSrc: 'https://www.hyundai.com/kr/ko/e/vehicles/the-all-new-palisade/catalog',
      },
    ],
  },
  {
    carName: '더 뉴 아이오닉 5',
    detailModels: [
      {
        carName: '더 뉴 아이오닉 5',
        modelName: 'E-Value +(스탠다드) 19인치',
        price: 49510000,
        imageSrc: 'https://www.hyundai.com/contents/vr360/NE04/trim/VV.png',
        interiorSrc: 'https://www.hyundai.com/contents/vr360/NE04/interior/I58/img-interior.png',
        catalogSrc: 'https://www.hyundai.com/kr/ko/e/vehicles/ioniq5/catalog',
      },
      {
        carName: '더 뉴 아이오닉 5',
        modelName: 'Exclusive(스탠다드) 19인치',
        price: 52560000,
        imageSrc: 'https://www.hyundai.com/contents/vr360/NE04/trim/VW.png',
        interiorSrc: 'https://www.hyundai.com/contents/vr360/NE04/interior/I58/img-interior.png',
        catalogSrc: 'https://www.hyundai.com/kr/ko/e/vehicles/ioniq5/catalog',
      },
      {
        carName: '더 뉴 아이오닉 5',
        modelName: 'E-Lite(롱레인지) 19인치',
        price: 53300000,
        imageSrc: 'https://www.hyundai.com/contents/vr360/NE04/trim/VH.png',
        interiorSrc: 'https://www.hyundai.com/contents/vr360/NE04/interior/I58/img-interior.png',
        catalogSrc: 'https://www.hyundai.com/kr/ko/e/vehicles/ioniq5/catalog',
      },
      {
        carName: '더 뉴 아이오닉 5',
        modelName: 'Exclusive(롱레인지) 19인치',
        price: 56980000,
        imageSrc: 'https://www.hyundai.com/contents/vr360/NE04/trim/VA.png',
        interiorSrc: 'https://www.hyundai.com/contents/vr360/NE04/interior/I58/img-interior.png',
        catalogSrc: 'https://www.hyundai.com/kr/ko/e/vehicles/ioniq5/catalog',
      },

      {
        carName: '더 뉴 아이오닉 5',
        modelName: '2WD',
        price: 57470000,
        imageSrc: 'https://www.hyundai.com/contents/vr360/NE04/trim/VF.png',
        interiorSrc: 'https://www.hyundai.com/contents/vr360/NE04/interior/I58/img-interior.png',
        catalogSrc: 'https://www.hyundai.com/kr/ko/e/vehicles/ioniq5/catalog',
      },
      {
        carName: '더 뉴 아이오닉 5',
        modelName: 'Prestige(롱레인지) 19인치',
        price: 61990000,
        imageSrc: 'https://www.hyundai.com/contents/vr360/NE04/trim/VG.png',
        interiorSrc: 'https://www.hyundai.com/contents/vr360/NE04/interior/I58/img-interior.png',
        catalogSrc: 'https://www.hyundai.com/kr/ko/e/vehicles/ioniq5/catalog',
      },
      {
        carName: '더 뉴 아이오닉 5',
        modelName: 'Prestige(롱레인지) 20인치',
        price: 62480000,
        imageSrc: 'https://www.hyundai.com/contents/vr360/NE04/trim/VB.png',
        interiorSrc: 'https://www.hyundai.com/contents/vr360/NE04/interior/I58/img-interior.png',
        catalogSrc: 'https://www.hyundai.com/kr/ko/e/vehicles/ioniq5/catalog',
      },
      {
        carName: '더 뉴 아이오닉 5',
        modelName: '롱레인지 20인치 N Line',
        price: 63150000,
        imageSrc: 'https://www.hyundai.com/contents/vr360/NE04/trim/VN.png',
        interiorSrc: 'https://www.hyundai.com/contents/vr360/NE04/interior/I58/img-interior.png',
        catalogSrc: 'https://www.hyundai.com/kr/ko/e/vehicles/ioniq5/catalog',
      },
    ],
  },
  {
    carName: '스타리아 킨더',
    detailModels: [
      {
        carName: '스타리아 킨더',
        modelName: 'Modern',
        price: 36430000,
        imageSrc: 'https://www.hyundai.com/contents/vr360/US25/trim/TM.png',
        interiorSrc: 'https://www.hyundai.com/contents/vr360/NE04/interior/I58/img-interior.png',
      },
      {
        carName: '스타리아 킨더',
        modelName: 'Modern',
        price: 39050000,
        imageSrc: 'https://www.hyundai.com/contents/vr360/US25/trim/TM.png',
        interiorSrc: 'https://www.hyundai.com/contents/vr360/NE04/interior/I58/img-interior.png',
      },
    ],
  },
  {
    carName: '활어 운반 차',
    detailModels: [
      {
        carName: '활어 운반 차',
        modelName: 'Smart',
        price: 3952700000,
        imageSrc: 'https://www.hyundai.com/contents/vr360/M586/trim/LM.png',
        interiorSrc: 'https://www.hyundai.com/contents/vr360/NE04/interior/I58/img-interior.png',
      },
    ],
  },
];

export default carDetailModels;
